{% set name = "threeml" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/threeML-{{ version }}.tar.gz
  sha256: 3ca1527669fdbab3c97157f719a9734c7b34c0dcd9712df14e60d313a7aa3227

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - asciitree
    - astromodels
    - astropy >=1.3.3
    - astroquery
    - colorama
    - corner
    - dill
    - dynesty
    - emcee >=3
    - iminuit >=2.0
    - ipyparallel
    - ipython
    - ipywidgets
    - matplotlib-base
    - numba
    - numdifftools
    - numexpr
    - numpy >=1.16
    - omegaconf
    - pandas
    - python >=3.6
    - pyyaml >=5.1
    - requests
    - rich
    - scipy >=0.18
    - speclite >=0.11
    - tqdm >=4.56.0
    - uncertainties

test:
  imports:
    - threeML
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/threeml/threeML
  summary: The Multi-Mission Maximum Likelihood framework
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
