{% set name = "threeml" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fb365a72814d55e50c09d582ec1014c60713cd86649a427977d8023875a24df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools <82
    - versioneer
  run:
    - packaging
    - astropy
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.13
    - emcee >3
    - astropy-base
    - matplotlib-base
    - uncertainties
    - pyyaml >=5.1
    - dill
    - iminuit >=2.0
    - astromodels
    - astroquery
    - corner
    - pandas
    - requests
    - speclite >=0.20
    - ipython
    - ipyparallel
    - joblib
    - numexpr
    - dynesty
    - numba
    - numdifftools
    - tqdm >=4.67.2
    - colorama
    - omegaconf
    - ipywidgets
    - rich
    - setuptools <82

test:
  imports:
    - threeML
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/threeml/threeML
  summary: The Multi-Mission Maximum Likelihood framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
